import os
import re
import requests
import pandas as pd
import time
from dotenv import load_dotenv
from datetime import datetime

load_dotenv()

TOKEN = os.getenv("GITHUB_TOKEN")
URL = "https://api.github.com/graphql"

headers = {
    "Authorization": f"Bearer {TOKEN}"
}

before_start = "2023-12-18T00:00:00Z"
before_end   = "2024-12-17T23:59:59Z"

after_start  = "2024-12-18T00:00:00Z"
after_end    = "2025-12-17T23:59:59Z"

AI_PATTERNS = {
    "copilot": [
        r"\bcopilot\b",
        r"github copilot"
    ],
    "chatgpt": [
        r"\bchatgpt\b",
        r"openai"
    ],
    "claude": [
        r"\bclaude\b",
        r"anthropic"
    ],
    "gemini": [
        r"\bgemini\b",
        r"\bbard\b"
    ],
    "bing": [
        r"\bbing\b",
        r"microsoft ai"
    ],
    "grok": [
        r"\bgrok\b",
        r"\bxai\b"
    ],
    "other_tools": [
        r"codewhisperer",
        r"tabnine",
        r"ghostwriter",
        r"replit ai"
    ],
    "general_ai": [
        r"ai[- ]?generated",
        r"generated by ai",
        r"ai[- ]?assisted",
        r"\bllm\b",
        r"large language model",
        r"using ai",
        r"written by ai"
    ]
}

commit_query = """
query ($login:String!) {
  user(login:$login) {
    repositories(first:100, ownerAffiliations:OWNER) {
      nodes {
        defaultBranchRef {
          target {
            ... on Commit {

              before: history(since:"%s", until:"%s", first:100) {
                nodes {
                  message
                  committedDate
                }
              }

              after: history(since:"%s", until:"%s", first:100) {
                nodes {
                  message
                  committedDate
                }
              }

            }
          }
        }
      }
    }
  }
}
""" % (before_start, before_end, after_start, after_end)

def run_query(query, variables, retries=3):
    for attempt in range(retries):
        try:
            r = requests.post(
                URL,
                json={"query": query, "variables": variables},
                headers=headers,
                timeout=20
            )

            if r.status_code != 200:
                raise Exception(r.text)

            return r.json()

        except Exception as e:
            print(f"Retry {attempt+1} failed:", e)
            time.sleep(2)

    raise Exception("Failed after retries")

def analyze_commits(commits):

    ai_count = 0
    category_counts = {k: 0 for k in AI_PATTERNS.keys()}
    first_seen = None

    for c in commits:
        msg = c.get("message", "").lower()
        date_str = c.get("committedDate")

        if not date_str:
            continue

        date = datetime.fromisoformat(date_str.replace("Z", "+00:00"))

        matched_categories = set()

        for category, patterns in AI_PATTERNS.items():
            for pattern in patterns:
                if re.search(pattern, msg):
                    matched_categories.add(category)
                    break

        if matched_categories:
            ai_count += 1

            for cat in matched_categories:
                category_counts[cat] += 1

            if first_seen is None or date < first_seen:
                first_seen = date

    return ai_count, category_counts, first_seen

def get_ai_metrics(username):
    result = run_query(commit_query, {"login": username})
    user_data = result.get("data", {}).get("user")

    if not user_data:
        return None

    repos = user_data["repositories"]["nodes"]
    commits_before = []
    commits_after = []

    for r in repos:
        branch = r.get("defaultBranchRef")
        if not branch:
            continue

        target = branch.get("target")
        if not target:
            continue

        commits_before.extend(target.get("before", {}).get("nodes", []))
        commits_after.extend(target.get("after", {}).get("nodes", []))

    ai_before, cat_before, first_before = analyze_commits(commits_before)
    ai_after, cat_after, first_after = analyze_commits(commits_after)

    combined_categories = {
        k: cat_before.get(k, 0) + cat_after.get(k, 0)
        for k in AI_PATTERNS.keys()
    }

    first_seen = None
    for f in [first_before, first_after]:
        if f:
            first_seen = f if first_seen is None else min(first_seen, f)

    metrics = {
        "ai_commit_count_before": ai_before,
        "ai_commit_count_after": ai_after,
        "ai_first_seen": first_seen
    }

    for cat in AI_PATTERNS.keys():
        metrics[f"mentions_{cat}"] = combined_categories[cat]
        metrics[f"mentions_{cat}_before"] = cat_before.get(cat, 0)
        metrics[f"mentions_{cat}_after"] = cat_after.get(cat, 0)

    return metrics

def main():

    #input_disabled = "../pr_activity/github_users_with_prs.csv"
    input_non_disabled = "../pr_activity/non_disabled_github_users_with_prs.csv"
    #output_disabled = "github_users_with_ai_signals.csv"
    output_non_disabled = "non_disabled_github_users_with_ai_signals.csv"

    #df_disabled = pd.read_csv(input_disabled)
    df_non_disabled = pd.read_csv(input_non_disabled)

    df_non_disabled["ai_commit_count_before"] = 0
    df_non_disabled["ai_commit_count_after"] = 0
    df_non_disabled["ai_commit_ratio_before"] = 0.0
    df_non_disabled["ai_commit_ratio_after"] = 0.0
    df_non_disabled["ai_first_seen"] = None

    categories = list(AI_PATTERNS.keys())

    for cat in categories:
        df_non_disabled[f"mentions_{cat}"] = 0
        df_non_disabled[f"mentions_{cat}_before"] = 0
        df_non_disabled[f"mentions_{cat}_after"] = 0

    for i, row in df_non_disabled.iterrows():

        username = row["username"]
        print(f"Processing {i+1}/{len(df_non_disabled)}: {username}")

        try:
            metrics = get_ai_metrics(username)

            if metrics is None:
                continue

            for k, v in metrics.items():
                df_non_disabled.at[i, k] = v

            cb = row.get("commits_before", 0)
            ca = row.get("commits_after", 0)

            df_non_disabled.at[i, "ai_commit_ratio_before"] = (
                metrics["ai_commit_count_before"] / cb if cb else 0
            )

            df_non_disabled.at[i, "ai_commit_ratio_after"] = (
                metrics["ai_commit_count_after"] / ca if ca else 0
            )

        except Exception as e:
            print("Error:", username, e)
            continue

        if i % 10 == 0:
            df_non_disabled.to_csv(output_non_disabled, index=False)

        time.sleep(0.5)

    df_non_disabled.to_csv(output_non_disabled, index=False)

if __name__ == "__main__":
    main()